#!/usr/bin/ruby
ENV['TZ'] = 'Australia/Brisbane'
now = Time.now
#if now.hour >= 0 and now.hour <= 8
  spares = 0
#elsif now.hour >= 9 and now.hour <= 10 and now.sunday?
#  spares = 0
#else
#  spares = 1
#end
out = nil
IO.popen('psql control', 'r+') do |p|
  p.puts("update config set value = '#{spares}' where key = 'pool_spares';")
  p.close_write
  out = p.read
end
raise "psql command failed: exit status = #{$?}:\n#{out}" if $? != 0
